# Generated by Django 5.1.4 on 2024-12-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(null=True, upload_to='products/')),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
